name: Unit tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest   
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
      - name: Run unit tests
        run: |
          python3 -m unittest test_create_release_notes.py